apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-docker-job
  labels:
    identifier: ""
spec:
  template:
    metadata:
      labels:
        identifier: ""
    spec:
      restartPolicy: Never
      containers:
      - name: flow-container
        image: ""
        command: []
        args: []
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
      - name: dind-daemon
        image: docker:18.09.4-dind
        env: []
        resources:
          requests:
            cpu: 20m
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-graph-store
            mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-store
          emptyDir: {}